# -*- coding: utf-8 -*-
"""ppo_gymnasium_sb3_01.ipynb

Automatically generated by Colab.

"""

# ---------  Algoritmo PPO aplicado a robot caminante  -------- #
#
# ------  UBA - Aprendizaje por Refuerzo II - 2025  ------ #
#

!apt-get update > /dev/null 2>&1
!apt-get install -y xvfb python-opengl ffmpeg swig build-essential > /dev/null 2>&1
!pip install swig > /dev/null 2>&1
!pip install gymnasium[box2d] > /dev/null 2>&1
!pip install stable-baselines3[extra] moviepy > /dev/null 2>&1
!pip install pyvirtualdisplay > /dev/null 2>&1
print("--- Instalación de dependencias completada ---")

import os
import gymnasium
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import VecVideoRecorder

print("Stable Baselines3 importado correctamente.")

env_id = 'BipedalWalker-v3'
video_folder = 'logs/videos/'
video_length = 1000
log_dir = "/tmp/gym/"
os.makedirs(log_dir, exist_ok=True)
os.makedirs(video_folder, exist_ok=True)

train_env = make_vec_env(env_id, n_envs=4)
record_env_raw = gymnasium.make(env_id, render_mode='rgb_array')

model = PPO(
    policy='MlpPolicy',
    env=train_env,
    learning_rate=3e-4,
    n_steps=2048,
    batch_size=64,
    n_epochs=10,
    gamma=0.99,
    gae_lambda=0.95,
    clip_range=0.2,
    ent_coef=0.0,
    vf_coef=0.5,
    max_grad_norm=0.5,
    verbose=1,
    seed=42,
)


print(f"Iniciando entrenamiento con PPO en {env_id}...")
model.learn(total_timesteps=500_000)
print("Entrenamiento completado.")

print(f"Grabando video de {env_id}...")
record_env = VecVideoRecorder(make_vec_env(lambda: record_env_raw, n_envs=1), video_folder,
                           record_video_trigger=lambda x: x == 0, video_length=video_length,
                           name_prefix=f"ppo-{env_id}")

obs = record_env.reset()
for _ in range(video_length + 1):
    action, _ = model.predict(obs, deterministic=True)
    obs, rewards, dones, info = record_env.step(action)
    if dones[0]:
        break

record_env.close()
print(f"Video guardado en la carpeta: {video_folder}")