# -*- coding: utf-8 -*-
"""stag_hare_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WEisS229e8pFeYQrL9FwXziperafYzG-
"""

import numpy as np

# Acciones
STAG = 0   # cooperar (mayor recompensa si ambos lo hacen)
HARE = 1   # actuar solo (menor pero segura)

# Recompensas del juego de Stag Hunt
# R[mi_acción][acción_del_otro]
reward_matrix = {
    STAG: {STAG: 4, HARE: 0},  # si ambos cazan ciervo => 4
    HARE: {STAG: 3, HARE: 3},
}

# Estrategias: probabilidades de elegir STAG
agent1_policy = 0.5
agent2_policy = 0.5

# Simulación
episodes = 100
agent1_total = 0
agent2_total = 0

for _ in range(episodes):
    a1 = np.random.choice([STAG, HARE], p=[agent1_policy, 1 - agent1_policy])
    a2 = np.random.choice([STAG, HARE], p=[agent2_policy, 1 - agent2_policy])

    r1 = reward_matrix[a1][a2]
    r2 = reward_matrix[a2][a1]

    agent1_total += r1
    agent2_total += r2

print(f"Agent 1 average reward: {agent1_total / episodes:.2f}")
print(f"Agent 2 average reward: {agent2_total / episodes:.2f}")